server:
  port: 9140

spring:
  application: 
    name: chl-npb-tributarydocumentation
  config:
    activate:
      on-profile: local
  main:
    allow-bean-definition-overriding: true

springdoc:
  title: chl-npb-tributarydocumentation
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

config:
  service-test: false
  git:
    load-flows: true
    repository: http://pdmtdagap01.cl.bsch/OperationsAndExecution/ApiProcess/chl-npb-tributarydocumentation
    user: n960929
    password: Leonardo5*
    branch: flows
    location: /tmp/repo/
    directory: dev/
    resource-file-extension: ^.*\.(groovy|java|yaml)$
    resource-folder-name: (transform)
  local:
    load-flows: true
    repository: /src/main/resources
    resource-file-extension: ^.*\.(groovy|java|yaml)$

camel:
  springboot:
    main-run-controller: true
    routes-include-pattern: classpath:routing/*
  threadpool:
    pool-size: 100
    max-pool-size: 500
  threads-concurrency-max: 5000
  seda-timeout: 500
  resilience4j:
    timeoutEnabled: true
    failureRateThreshold: 99
    waitDurationInOpenState: 5
    automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    root: INFO
    com.santander.application.routing.ServiceRouting: DEBUG
    com.santander.application.beans.*: DEBUG
    
app:
  logging:
    file:
      enabled: false
      dir: log
    logging:
      root-level: ERROR

beans:
  webclient:
    max-in-memory-size: 512
  server:
    host: 0.0.0.0
    port: 9150
    chunked-max-content-length: 50
  context:
    url: https://dss-context-service-dss-pre.apps.chi01.chi.pre.cl1.paas.cloudcenter.corp/v1/context
    default-map: session
    default-ttl: 600000
    default-key: token
  b2h:
    endpoint: rest:post:api/b2h?host=b2h.dcloud.cl.bsch
    on-fallback-endpoint: rest:post:api/b2h?host=b2h.dcloud.cl.bsch
  b2d:
    endpoint: rest:post:api/b2d?host=b2dhcf.hcloud.cl.bsch
    on-fallback-endpoint: rest:post:api/b2d?host=b2dhcf.hcloud.cl.bsch
    #endpoint: rest:post:api/b2d?host=beaas.pri.dcloud.cl.bsch
    #on-fallback-endpoint: rest:post:api/b2d?host=beaas.pri.dcloud.cl.bsch
  transform:
    example-name:
      endpoint: jslt:transform/example-name.jslt?allowContextMapAll=true
  functional-log:
    event-1:
      transform: jslt:transform/functional-log/event-1.jslt
      endpoint: kafka:log-func-${spring.application.name}?brokers=dctamsbnr01.cl.bsch:9092
      on-fallback-endpoint: kafka:log-func-${spring.application.name}?brokers=dctamsbnr01.cl.bsch:9092
  rest:
    ffmm-tributarycertificates-list:
      endpoint: https://chl-dss-mutualfundadmin-market-operations-pre.apps.chi01.chi.pre.cl1.paas.cloudcenter.corp/v1/mutual-funds/customers/certificates/cert-ffmm-1922
      method: get
    57bis-data:
      endpoint: https://chl-dss-mutualfundadmin-market-operations-pre.apps.chi01.chi.pre.cl1.paas.cloudcenter.corp/v1/mutual-funds/customers/certificates/cert-ffmm-57bis?yearid={yearid}
      method: get
    1922-data:
      endpoint: https://chl-dss-mutualfundadmin-market-operations-pre.apps.chi01.chi.pre.cl1.paas.cloudcenter.corp/v1/mutual-funds/customers/certificates/cert-ffmm-1922
      method: get
    1984-data:
      endpoint: https://chl-dss-mutualfundadmin-market-operations-pre.apps.chi01.chi.pre.cl1.paas.cloudcenter.corp/v1/investments/customers/tributary-certificates
      method: get
    document-create-base64:
      endpoint: https://api-gesdoc-service-document-mgmt-archive-pre.apps.chi01.chi.pre.cl1.paas.cloudcenter.corp/v1/pi-connector/base64
      method: post